# Data Filtering with Pandas

Author: Gaurav Gohil

Filtering is an important technique in data analysis that allows us to extract specific rows and columns based on conditions.

Using Pandas, we can easily filter datasets using logical conditions and built-in methods.

---

## Topics Covered

1. Creating a Sample Dataset
2. Filtering Rows
3. Filtering with Multiple Conditions
4. Using loc
5. Using iloc
6. Sorting Data

In [1]:
import pandas as pd

## 1. Creating a Sample Dataset

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [24, 27, 22, 32, 29],
    "City": ["New York", "London", "Paris", "Tokyo", "Berlin"],
    "Salary": [50000, 60000, 45000, 70000, 65000]
}

df = pd.DataFrame(data)

df

      Name  Age      City  Salary
0    Alice   24  New York   50000
1      Bob   27    London   60000
2  Charlie   22     Paris   45000
3    David   32     Tokyo   70000
4      Eva   29    Berlin   65000

## 2. Filtering Rows

We can filter rows based on conditions.

In [3]:
df[df["Age"] > 25]

    Name  Age    City  Salary
1    Bob   27  London   60000
3  David   32   Tokyo   70000
4    Eva   29  Berlin   65000

## 3. Filtering with Multiple Conditions

In [4]:
df[(df["Age"] > 25) & (df["Salary"] > 60000)]

    Name  Age    City  Salary
3  David   32   Tokyo   70000
4    Eva   29  Berlin   65000

## 4. Using loc

The `loc` method is used to select rows and columns by labels.

In [5]:
df.loc[df["Age"] > 25, ["Name", "Salary"]]

    Name  Salary
1    Bob   60000
3  David   70000
4    Eva   65000

## 5. Using iloc

The `iloc` method selects rows and columns based on their index positions.

In [7]:
df.iloc[0:3, 0:2]

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22

## 6. Sorting Data

In [8]:
df.sort_values(by="Salary")

      Name  Age      City  Salary
2  Charlie   22     Paris   45000
0    Alice   24  New York   50000
1      Bob   27    London   60000
4      Eva   29    Berlin   65000
3    David   32     Tokyo   70000

In [9]:
df.sort_values(by="Salary", ascending=False)

      Name  Age      City  Salary
3    David   32     Tokyo   70000
4      Eva   29    Berlin   65000
1      Bob   27    London   60000
0    Alice   24  New York   50000
2  Charlie   22     Paris   45000

## 7. Filtering by Specific Values

In [10]:
df[df["City"] == "London"]

  Name  Age    City  Salary
1  Bob   27  London   60000

## Conclusion

In this notebook we learned:

- Filtering rows based on conditions
- Filtering with multiple conditions
- Using loc and iloc
- Sorting datasets
- Filtering by specific values

These operations are commonly used during data analysis and exploratory data analysis (EDA).