# Data Cleaning with Pandas

Author: Gaurav Gohil

Data cleaning is a crucial step in the data analysis process.  
Real-world datasets often contain missing values, duplicate records, or inconsistent data types.

Pandas provides powerful tools to clean and preprocess data efficiently.

---

## Topics Covered

1. Creating a Sample Dataset
2. Identifying Missing Values
3. Handling Missing Values
4. Removing Duplicate Rows
5. Changing Data Types
6. Renaming Columns

In [8]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

## 1. Creating a Sample Dataset

For demonstration purposes, we will create a small dataset containing missing values and duplicates.

In [9]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Alice"],
    "Age": [24, np.nan, 22, 32, 24],
    "City": ["New York", "London", "Paris", None, "New York"],
    "Salary": [50000, 60000, None, 70000, 50000]
}

df = pd.DataFrame(data)

df

      Name   Age      City   Salary
0    Alice  24.0  New York  50000.0
1      Bob   NaN    London  60000.0
2  Charlie  22.0     Paris      NaN
3    David  32.0      None  70000.0
4    Alice  24.0  New York  50000.0

## 2. Identifying Missing Values

We can check for missing values using the `isnull()` function.

In [10]:
df.isnull()

    Name    Age   City  Salary
0  False  False  False   False
1  False   True  False   False
2  False  False  False    True
3  False  False   True   False
4  False  False  False   False

In [11]:
df.isnull().sum()

Name      0
Age       1
City      1
Salary    1
dtype: int64

## 3. Handling Missing Values

There are multiple ways to handle missing values in a dataset.

### Removing Rows with Missing Values

In [12]:
df_dropna = df.dropna()

df_dropna

    Name   Age      City   Salary
0  Alice  24.0  New York  50000.0
4  Alice  24.0  New York  50000.0

### Filling Missing Values

In [13]:
df_filled = df.fillna("Unknown")

df_filled

      Name      Age      City   Salary
0    Alice     24.0  New York  50000.0
1      Bob  Unknown    London  60000.0
2  Charlie     22.0     Paris  Unknown
3    David     32.0   Unknown  70000.0
4    Alice     24.0  New York  50000.0

### Filling Missing Numeric Values with Mean

In [14]:
df["Age"].fillna(df["Age"].mean(), inplace=True)

df

      Name   Age      City   Salary
0    Alice  24.0  New York  50000.0
1      Bob  25.5    London  60000.0
2  Charlie  22.0     Paris      NaN
3    David  32.0      None  70000.0
4    Alice  24.0  New York  50000.0

## 4. Removing Duplicate Rows

Duplicate records can distort analysis results.

In [15]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [16]:
df_no_duplicates = df.drop_duplicates()

df_no_duplicates

      Name   Age      City   Salary
0    Alice  24.0  New York  50000.0
1      Bob  25.5    London  60000.0
2  Charlie  22.0     Paris      NaN
3    David  32.0      None  70000.0

## 5. Changing Data Types

Sometimes we need to convert columns to appropriate data types.

In [17]:
df["Age"] = df["Age"].astype(int)

df.dtypes

Name       object
Age         int64
City       object
Salary    float64
dtype: object

## 6. Renaming Columns

In [18]:
df.rename(columns={"Salary": "Annual_Salary"}, inplace=True)

df

      Name  Age      City  Annual_Salary
0    Alice   24  New York        50000.0
1      Bob   25    London        60000.0
2  Charlie   22     Paris            NaN
3    David   32      None        70000.0
4    Alice   24  New York        50000.0

## Conclusion

In this notebook we learned how to clean datasets using Pandas.

Key techniques covered:

- Identifying missing values
- Removing or filling missing data
- Removing duplicate rows
- Changing data types
- Renaming columns

Data cleaning is an essential step before performing data analysis or building machine learning models.