# GroupBy Operations in Pandas

Author: Gaurav Gohil

The `groupby()` function in Pandas allows us to group data based on specific columns and perform aggregation operations.

It is widely used in data analysis to summarize datasets.

---

## Topics Covered

1. Creating a Sample Dataset
2. Grouping Data
3. Aggregation Functions
4. Multiple Aggregations
5. Grouping by Multiple Columns

In [1]:
import pandas as pd

## 1. Creating a Sample Dataset

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [60000, 50000, 65000, 70000, 52000, 62000],
    "Age": [25, 28, 24, 35, 30, 27]
}

df = pd.DataFrame(data)

df

      Name Department  Salary  Age
0    Alice         IT   60000   25
1      Bob         HR   50000   28
2  Charlie         IT   65000   24
3    David    Finance   70000   35
4      Eva         HR   52000   30
5    Frank         IT   62000   27

## 2. Grouping Data

We can group data based on a column using the `groupby()` function.

In [3]:
df.groupby("Department")

## 3. Mean Salary by Department

In [4]:
df.groupby("Department")["Salary"].mean()

Department
Finance    70000.000000
HR         51000.000000
IT         62333.333333
Name: Salary, dtype: float64

## 4. Total Salary by Department

In [5]:
df.groupby("Department")["Salary"].sum()

Department
Finance     70000
HR         102000
IT         187000
Name: Salary, dtype: int64

## 5. Count Employees per Department

In [6]:
df.groupby("Department")["Name"].count()

Department
Finance    1
HR         2
IT         3
Name: Name, dtype: int64

## 6. Multiple Aggregations

In [7]:
df.groupby("Department")["Salary"].agg(["mean", "min", "max", "count"])

                    mean    min    max  count
Department
Finance     70000.000000  70000  70000      1
HR          51000.000000  50000  52000      2
IT          62333.333333  60000  65000      3

## 7. Grouping by Multiple Columns

In [8]:
df.groupby(["Department", "Age"])["Salary"].mean()

Department  Age
Finance     35     70000.0
HR          28     50000.0
            30     52000.0
IT          24     65000.0
            25     60000.0
            27     62000.0
Name: Salary, dtype: float64

## 8. Reset Index

In [9]:
grouped_data = df.groupby("Department")["Salary"].mean().reset_index()

grouped_data

  Department        Salary
0    Finance  70000.000000
1         HR  51000.000000
2         IT  62333.333333

## Conclusion

In this notebook we learned how to use the `groupby()` function in Pandas to perform data aggregation.

Key operations covered:

- Grouping datasets
- Mean, sum, and count aggregations
- Multiple aggregation functions
- Grouping by multiple columns

GroupBy operations are widely used in **data analysis, business intelligence, and machine learning workflows**.