# Pandas Basics for Data Analysis

Author: Gaurav Gohil

Pandas is one of the most widely used Python libraries for data analysis and data manipulation.  
It provides powerful data structures such as **Series** and **DataFrame** that make working with structured data easier.

---

## Topics Covered

1. Introduction to Pandas
2. Creating a Pandas Series
3. Creating a DataFrame
4. Reading Data from CSV
5. Exploring Data
6. Selecting Columns
7. Filtering Data

In [1]:
import pandas as pd

## 1. Creating a Pandas Series

A **Series** is a one-dimensional labeled array capable of holding any data type.

In [2]:
data = [10, 20, 30, 40, 50]

series = pd.Series(data)

series

0    10
1    20
2    30
3    40
4    50
dtype: int64

## 2. Creating a DataFrame

A **DataFrame** is a two-dimensional table-like data structure consisting of rows and columns.

In [3]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "City": ["New York", "London", "Paris", "Tokyo"]
}

df = pd.DataFrame(data)

df

      Name  Age      City
0    Alice   24  New York
1      Bob   27    London
2  Charlie   22     Paris
3    David   32     Tokyo

## 3. Viewing Data

Pandas provides several methods to quickly inspect the dataset.

In [4]:
df.head()

      Name  Age      City
0    Alice   24  New York
1      Bob   27    London
2  Charlie   22     Paris
3    David   32     Tokyo

In [5]:
df.tail()

      Name  Age      City
0    Alice   24  New York
1      Bob   27    London
2  Charlie   22     Paris
3    David   32     Tokyo

## 4. Dataset Information

We can get information about the dataset structure.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [7]:
df.describe()

             Age
count   4.000000
mean   26.250000
std     4.349329
min    22.000000
25%    23.500000
50%    25.500000
75%    28.250000
max    32.000000

## 5. Selecting Columns

We can select specific columns from a DataFrame.

In [8]:
df["Name"]

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [9]:
df[["Name", "Age"]]

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
3    David   32

## 6. Selecting Rows

Rows can be selected using the **iloc** method (integer position).

In [10]:
df.iloc[0]

Name       Alice
Age           24
City    New York
Name: 0, dtype: object

In [11]:
df.iloc[1:3]

      Name  Age    City
1      Bob   27  London
2  Charlie   22   Paris

## 7. Filtering Data

We can filter data using conditional expressions.

In [12]:
df[df["Age"] > 25]

    Name  Age    City
1    Bob   27  London
3  David   32   Tokyo

## 8. Adding a New Column

In [13]:
df["Salary"] = [50000, 60000, 45000, 70000]

df

      Name  Age      City  Salary
0    Alice   24  New York   50000
1      Bob   27    London   60000
2  Charlie   22     Paris   45000
3    David   32     Tokyo   70000

## 9. Basic Data Analysis

In [14]:
df["Age"].mean()

np.float64(26.25)

## Conclusion

In this notebook we explored the basics of Pandas including:

- Series
- DataFrame
- Viewing data
- Selecting rows and columns
- Filtering data
- Adding new columns
- Basic analysis

Pandas is an essential tool for **data cleaning, transformation, and analysis** in Data Science.